services:
  ticket-database:
    image: postgres:16
    container_name: ticket-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tickets
    ports:
      - "5432:5432"
  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro